# Generated by Django 3.1.2 on 2022-11-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='formatted_name',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('project_path', 'name')},
        ),
    ]
