# Generated by Django 3.1.2 on 2022-11-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0002_auto_20221113_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='formatted_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
