# Generated by Django 3.1.3 on 2020-11-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0002_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='settingheader',
            options={'ordering': ('project__name',)},
        ),
        migrations.AlterModelOptions(
            name='settingvalue',
            options={'ordering': ('name',)},
        ),
    ]
