# Generated by Django 3.1.2 on 2021-12-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0003_auto_20201109_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingheader',
            name='value',
            field=models.TextField(),
        ),
    ]
