# Generated by Django 3.1.2 on 2022-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0004_auto_20221209_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='packages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
