# Generated by Django 3.1.2 on 2021-12-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0004_auto_20211231_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingvalue',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
