# Generated by Django 3.1.2 on 2022-12-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0005_projectsettings_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectauth',
            name='access_expiry',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='projectauth',
            name='refresh_expiry',
            field=models.PositiveIntegerField(default=365),
        ),
    ]
