# Generated by Django 3.1.2 on 2022-12-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0006_auto_20221211_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_migration',
            field=models.BooleanField(default=False),
        ),
    ]
