# Generated by Django 3.1.2 on 2022-12-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0007_project_has_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettings',
            name='packages',
        ),
    ]
