# Generated by Django 3.1.2 on 2022-06-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0007_auto_20220622_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_path',
            field=models.TextField(default='/Users/adefemioseni/Desktop/djuix_test_projects', editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together={('project_id', 'name')},
        ),
    ]
