# Generated by Django 3.1.2 on 2022-12-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0008_remove_projectsettings_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectauth',
            name='default_auth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
