# Generated by Django 3.1.2 on 2022-06-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0008_auto_20220622_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', editable=False, max_length=50),
        ),
    ]
