# Generated by Django 3.1.4 on 2022-12-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0010_auto_20221221_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_path',
            field=models.TextField(default='/djuix-files'),
        ),
    ]
