# Generated by Django 3.1.2 on 2022-06-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0010_auto_20220622_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
