# Generated by Django 3.1.2 on 2022-06-24 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0011_auto_20220622_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='settingvalue',
            name='project',
        ),
        migrations.AddField(
            model_name='app',
            name='formatted_name',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='formatted_name',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='SettingHeader',
        ),
        migrations.DeleteModel(
            name='SettingValue',
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_setting', to='project_controller.project'),
        ),
    ]
