# Generated by Django 3.1.4 on 2023-01-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0011_auto_20221229_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='changed_storage',
            field=models.BooleanField(default=False),
        ),
    ]
