# Generated by Django 3.1.2 on 2022-07-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0012_auto_20220624_1057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='app',
            unique_together={('project_id', 'formatted_name')},
        ),
    ]
