# Generated by Django 3.1.2 on 2022-07-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0013_auto_20220701_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='formatted_name',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
