# Generated by Django 3.1.2 on 2022-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0014_auto_20220701_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='run_migration',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
