# Generated by Django 3.1.2 on 2022-07-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0016_auto_20220719_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='run_migration',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
