# Generated by Django 3.1.2 on 2022-07-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0019_auto_20220719_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
