# Generated by Django 3.1.4 on 2022-12-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20221113_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='removed_folder',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
