# Generated by Django 3.1.4 on 2022-12-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20221228_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unique_username',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
