# Generated by Django 3.1.4 on 2022-12-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_customuser_unique_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='unique_username',
        ),
    ]
