# Generated by Django 3.1.4 on 2022-12-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_customuser_unique_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='removed_folder',
            field=models.BooleanField(default=False),
        ),
    ]
