# Generated by Django 3.1.4 on 2023-01-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='operation',
            field=models.CharField(choices=[('CREATE_PROJECT', 'CREATE_PROJECT'), ('CREATE_AUTH', 'CREATE_AUTH')], max_length=50),
        ),
    ]
