# Generated by Django 3.1.4 on 2023-03-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0016_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='project_count',
            field=models.IntegerField(default=2),
        ),
    ]
