# Generated by Django 3.1.2 on 2022-11-09 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_controller', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_properties', models.JSONField(default=None, null=True)),
                ('has_created_migration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_models', to='project_controller.app')),
            ],
            options={
                'ordering': ('created_at',),
                'unique_together': {('app_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SerializerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_properties', models.JSONField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_serializers', to='project_controller.app')),
                ('model_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_serializers', to='app_controller.modelinfo')),
            ],
            options={
                'unique_together': {('app_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ViewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_properties', models.JSONField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_views', to='project_controller.app')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_views', to='app_controller.modelinfo')),
                ('serializer_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serializer_views', to='app_controller.serializerinfo')),
            ],
            options={
                'ordering': ('created_at',),
                'unique_together': {('app_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UrlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_properties', models.JSONField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_urls', to='project_controller.app')),
                ('view_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_urls', to='app_controller.viewsinfo')),
            ],
            options={
                'unique_together': {('app_id', 'name')},
            },
        ),
    ]
