# Generated by Django 3.1.3 on 2020-11-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_controller', '0003_auto_20201109_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_models', to='project_controller.app')),
            ],
        ),
        migrations.CreateModel(
            name='ModelFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_null', models.BooleanField(default=False)),
                ('is_blank', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('helper_text', models.TextField(blank=True, null=True)),
                ('max_length', models.IntegerField(null=True)),
                ('is_related', models.BooleanField(default=False)),
                ('related_model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('related_name_main', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_fields', to='app_controller.modelinfo')),
            ],
        ),
    ]
