# Generated by Django 3.1.3 on 2020-11-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelFields',
            new_name='ModelField',
        ),
    ]
