# Generated by Django 3.1.3 on 2020-11-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0002_auto_20201122_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfield',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'CharField'), ('TextField', 'TextField')], default='CharField', max_length=50),
        ),
    ]
