# Generated by Django 3.1.3 on 2020-11-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0003_modelfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfield',
            name='is_created_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelfield',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'CharField'), ('TextField', 'TextField'), ('DateTimeField', 'DateTimeField')], default='CharField', max_length=50),
        ),
    ]
