# Generated by Django 3.1.3 on 2020-11-23 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0003_auto_20201109_0531'),
        ('app_controller', '0004_auto_20201122_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerializerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_serializers', to='project_controller.app')),
                ('model_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_serializers', to='app_controller.modelinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SerializerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('CharField', 'CharField'), ('TextField', 'TextField'), ('DateTimeField', 'DateTimeField')], default='CharField', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('is_write_only', models.BooleanField(default=False)),
                ('is_read_only', models.BooleanField(default=False)),
                ('is_related', models.BooleanField(default=False)),
                ('related_serializer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_many', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serializer_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serializer_fields', to='app_controller.modelinfo')),
            ],
        ),
    ]
