# Generated by Django 3.1.3 on 2020-11-23 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0005_serializerfield_serializerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerfield',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serializerfield',
            name='serializer_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serializer_fields', to='app_controller.serializerinfo'),
        ),
    ]
