# Generated by Django 3.1.2 on 2022-09-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0007_auto_20220613_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewsinfo',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='has_created_migration',
            field=models.BooleanField(default=False),
        ),
    ]
