version: '3'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: djuix_api
    restart: unless-stopped
    volumes:
      - .:/djuix
      - ${DJUIX_FILES}:/djuix-files
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - djuix_net
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: djuix_postgres_db
    image: postgres:13.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/djuix_postgres_db
    volumes:
       - djuix_postgres_db:/data/djuix_postgres_db
    networks:
      - djuix_net
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks:
      - djuix_net

  celery:
    build: .
    command: celery -A djuix worker -l info
    volumes:
      - .:/djuix
      - ${DJUIX_FILES}:/djuix-files
    restart: always
    networks:
      - djuix_net
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  beats:
    build: .
    command: celery -A djuix beat -l info
    volumes:
      - .:/djuix
      - ${DJUIX_FILES}:/djuix-files
    restart: always
    networks:
      - djuix_net
    env_file:
      - .env
    depends_on:
      - redis
      - postgres


networks:
  djuix_net:
    driver: bridge

volumes:
    djuix_postgres_db: